import type { ContentBrief, BriefStatus } from '@/types/agent2'
import { briefTemplates, geoChecklist, sampleOpportunities } from '@/data/agent2Data'

// Creates a ContentBrief from a template — no LLM, fully deterministic
export function generateBrief(opportunityId: string, status: BriefStatus = 'Draft'): ContentBrief | null {
  const template = briefTemplates[opportunityId]
  const opportunity = sampleOpportunities.find(o => o.id === opportunityId)
  if (!template || !opportunity) return null

  return {
    opportunityId,
    opportunityLabel: opportunity.label,
    generatedAt: new Date().toISOString(),
    status,
    geoChecklist,
    ...template,
  }
}

export function briefToMarkdown(brief: ContentBrief): string {
  const lines: string[] = []

  lines.push(`# Content Brief: ${brief.opportunityLabel}`)
  lines.push(``)
  lines.push(`**Status:** ${brief.status}  `)
  lines.push(`**Generated:** ${new Date(brief.generatedAt).toLocaleDateString('en-GB')}`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## 1. Content Objective`)
  lines.push(``)
  lines.push(brief.objective)
  lines.push(``)
  lines.push(`## 2. Target AI Search Queries`)
  lines.push(``)
  brief.targetQueries.forEach(q => lines.push(`- ${q}`))
  lines.push(``)
  lines.push(`## 3. Customer Insight`)
  lines.push(``)
  lines.push(brief.customerInsight)
  lines.push(``)
  lines.push(`## 4. Category Entry Point`)
  lines.push(``)
  lines.push(`**${brief.cep.label}**`)
  lines.push(``)
  lines.push(brief.cep.explanation)
  lines.push(``)
  lines.push(`## 5. Recommended Page Structure`)
  lines.push(``)
  brief.pageStructure.forEach(item => {
    if (item.type === 'h1') lines.push(`- **H1:** ${item.text}`)
    else if (item.type === 'cta') lines.push(`- **CTA:** ${item.text}`)
    else lines.push(`- ${item.text}`)
  })
  lines.push(``)
  lines.push(`## 6. AI-Optimized Answer Block`)
  lines.push(``)
  lines.push(`> ${brief.answerBlock}`)
  lines.push(``)
  lines.push(`## 7. FAQ Section`)
  lines.push(``)
  brief.faq.forEach((item, i) => {
    lines.push(`**Q${i + 1}: ${item.question}**`)
    lines.push(`${item.answer}`)
    lines.push(``)
  })
  lines.push(`## 8. Justification Attributes`)
  lines.push(``)
  brief.justificationAttributes.forEach(a => lines.push(`- ${a}`))
  lines.push(``)
  lines.push(`## 9. Required Evidence`)
  lines.push(``)
  brief.requiredEvidence.forEach(e => lines.push(`- ${e}`))
  lines.push(``)
  lines.push(`## 10. Competitor Angle`)
  lines.push(``)
  lines.push(brief.competitorAngle)
  lines.push(``)
  lines.push(`## 11. GEO/AEO Optimization Checklist`)
  lines.push(``)
  brief.geoChecklist.forEach(item => lines.push(`- [ ] ${item}`))
  lines.push(``)
  lines.push(`## 12. Schema Recommendations`)
  lines.push(``)
  lines.push(brief.schemaRecommendations.join(', '))
  lines.push(``)
  lines.push(`---`)
  lines.push(`*Generated by OHRA GEO Operating System — Agent 2 Content Briefs*`)
  lines.push(`*This brief requires human marketing and compliance review before any content is created.*`)

  return lines.join('\n')
}
