import type { ContentDraft, DraftStatus } from '@/types/agent3'
import { draftTemplates, draftOpportunities, geoItems } from '@/data/agent3Data'

// Creates a ContentDraft from the template — deterministic, no LLM needed
export function generateDraft(opportunityId: string, status: DraftStatus = 'Draft Generated'): ContentDraft | null {
  const template = draftTemplates[opportunityId]
  const opp = draftOpportunities.find(o => o.id === opportunityId)
  if (!template || !opp) return null

  return {
    opportunityId,
    opportunityLabel: opp.label,
    generatedAt: new Date().toISOString(),
    status,
    geoItems,
    ...template,
  }
}

// Converts a draft to a downloadable markdown file
export function draftToMarkdown(draft: ContentDraft): string {
  const lines: string[] = []
  const date = new Date(draft.generatedAt).toLocaleDateString('en-GB')

  lines.push(`# ${draft.h1}`)
  lines.push(``)
  lines.push(`> **DRAFT — NOT FOR PUBLICATION**  `)
  lines.push(`> Status: ${draft.status} · Generated: ${date}  `)
  lines.push(`> This draft requires human marketing and compliance review before any content is published.`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(draft.intro)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## Answer Block (AI-Optimized, 60–90 words)`)
  lines.push(``)
  lines.push(`> ${draft.answerBlock}`)
  lines.push(``)

  draft.sections.forEach(s => {
    lines.push(`## ${s.heading}`)
    lines.push(``)
    if (s.requiresProof) lines.push(`> ⚠️ **This section contains placeholders that require OHRA-specific proof before publishing.**`)
    lines.push(``)
    lines.push(s.body)
    lines.push(``)
  })

  if (draft.comparisonTable) {
    const t = draft.comparisonTable
    lines.push(`## ${t.caption}`)
    lines.push(``)
    lines.push(`| ${t.headers.join(' | ')} |`)
    lines.push(`| ${t.headers.map(() => '---').join(' | ')} |`)
    t.rows.forEach(row => lines.push(`| ${row.join(' | ')} |`))
    lines.push(``)
  }

  lines.push(`## Frequently Asked Questions`)
  lines.push(``)
  draft.faq.forEach((f, i) => {
    lines.push(`**Q${i + 1}: ${f.question}**`)
    lines.push(`${f.answer}`)
    lines.push(``)
  })

  lines.push(`## Call to Action`)
  lines.push(``)
  lines.push(draft.cta)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## ⚠️ Compliance Risk Notes`)
  lines.push(``)
  lines.push(`The following items must be verified by humans before this content is published:`)
  lines.push(``)
  draft.complianceNotes.forEach(n => lines.push(`- ${n}`))
  lines.push(``)
  lines.push(`---`)
  lines.push(`*Generated by OHRA GEO Operating System — Agent 3 Draft Writing*`)
  lines.push(`*For internal review only. Do not publish without compliance approval.*`)

  return lines.join('\n')
}
