import type { SampleOpportunity, ContentBrief } from '@/types/agent2'

// The 5 sample opportunities for Agent 2 — themeId matches Agent 1 theme IDs
export const sampleOpportunities: SampleOpportunity[] = [
  { id: 'young-drivers',  themeId: 'young-drivers',  label: 'Young Drivers',                   cep: 'Buying first car',                     intentStage: 'Consideration', gapLevel: 'High',   priorityScore: 87 },
  { id: 'coverage-type',  themeId: 'coverage-type',  label: 'WA vs WA+ vs All-risk',           cep: 'Choosing coverage level',              intentStage: 'Comparison',    gapLevel: 'High',   priorityScore: 82 },
  { id: 'ev-insurance',   themeId: 'ev-insurance',   label: 'Electric Vehicle Insurance',      cep: 'Switching to electric driving',        intentStage: 'Awareness',     gapLevel: 'High',   priorityScore: 91 },
  { id: 'claim-handling', themeId: 'claim-handling', label: 'Claim Handling After Accident',   cep: 'Accident or damage moment',            intentStage: 'Post-purchase / Claim', gapLevel: 'Medium', priorityScore: 76 },
  { id: 'switching',      themeId: 'switching',      label: 'Switching After Premium Increase', cep: 'Renewal or dissatisfaction moment',   intentStage: 'Purchase',      gapLevel: 'High',   priorityScore: 88 },
]

// GEO/AEO checklist — same for every brief (these are requirements, not a to-do list)
export const geoChecklist: string[] = [
  'Clear H1 with primary target keyword',
  'Direct short answer block within the first 2 paragraphs',
  'FAQ section with FAQPage schema markup',
  'Comparison table or structured checklist',
  'Correct Dutch insurance terminology (WA, all-risk, no-claim, etc.)',
  'Last reviewed / updated date shown on the page',
  'Internal links to related OHRA product pages',
  'Source or proof section (data, research, legal basis)',
  'Human compliance review completed before publishing',
]

// Brief template content — one per opportunity
// Generated by Agent 2 based on Agent 1 signals; not real OHRA claims
type BriefTemplate = Omit<ContentBrief, 'opportunityId' | 'opportunityLabel' | 'generatedAt' | 'status' | 'geoChecklist'>

export const briefTemplates: Record<string, BriefTemplate> = {
  'young-drivers': {
    objective:
      'Help young Dutch drivers (18–25) compare car insurance options and understand what coverage level suits their first car — positioning OHRA as a clear, trustworthy option in AI-generated answers.',

    targetQueries: [
      '"best car insurance for young drivers Netherlands"',
      '"cheap car insurance for 18-year-old Netherlands"',
      '"which car insurance for first car Netherlands"',
      '"autoverzekering jongeren vergelijken 2025"',
      '"why is car insurance so expensive for young drivers?"',
    ],

    customerInsight:
      'Young Dutch drivers are price-sensitive — age surcharges can double standard premiums. They are uncertain about the difference between WA, WA+, and All-risk, and actively compare options online and via AI assistants before buying. Many are buying their first car and need guidance, not sales language.',

    cep: {
      label: 'Buying a first car',
      explanation:
        'The moment a young person buys their first car is a high-intent trigger for insurance comparison. This is often their first interaction with an insurance brand. Winning here can mean a long-term customer relationship. Competitors are already visible at this moment.',
    },

    pageStructure: [
      { type: 'h1',    text: 'Best Car Insurance for Young Drivers in the Netherlands (2025)' },
      { type: 'block', text: 'Short answer block: direct 3-sentence answer for AI extraction' },
      { type: 'h2',    text: 'Why car insurance costs more for young drivers' },
      { type: 'h2',    text: 'WA, WA+ or All-risk: what does a young driver actually need?' },
      { type: 'h2',    text: 'How to lower your premium as a young driver' },
      { type: 'h2',    text: 'What OHRA offers young drivers [placeholder — requires compliance review]' },
      { type: 'h2',    text: 'Comparison checklist: what to look for' },
      { type: 'h2',    text: 'Frequently asked questions' },
      { type: 'cta',   text: 'Call to action: Get a quote / Compare options' },
    ],

    answerBlock:
      'Choosing car insurance as a young driver in the Netherlands is often expensive, but the right choice depends on your car\'s age, your budget, and your risk profile. Most young drivers start with WA (third-party only) or WA+ for older cars, and consider All-risk for newer or financed vehicles. Comparing insurers directly typically delivers the best premium. Building a no-claim history from year one is the fastest way to reduce costs over time.',

    faq: [
      { question: 'Why is car insurance more expensive for young drivers?',         answer: 'Insurance premiums are higher for young drivers because statistically, drivers under 25 have more accidents. Less driving experience means higher risk for the insurer, which is reflected directly in the premium.' },
      { question: 'What car insurance level is best for a first car?',              answer: 'For a first car (often older and lower in value), WA is usually the most affordable option. If your car is newer or financed, your lender may require WA+ or All-risk.' },
      { question: 'Can I reduce my premium as a young driver?',                     answer: 'Yes. Proven ways include choosing a lower-powered car, increasing your voluntary excess, paying annually rather than monthly, and building a no-claim record from year one.' },
      { question: 'How does no-claim discount work for young drivers?',             answer: 'No-claim discounts reward claim-free years with lower premiums. Even as a young driver you start building from year one. After five claim-free years, discounts can be substantial.' },
      { question: 'Can I drive my parents\' car and be insured?',                  answer: 'Not automatically. If you are not named on your parents\' policy as an occasional driver, you may not be covered. Always confirm with the insurer.' },
      { question: 'Do I need to tell my insurer about points on my licence?',       answer: 'Yes. Most policies require you to disclose driving convictions. Failure to do so can give the insurer grounds to void your policy.' },
      { question: 'What happens to my premium after my first claim?',               answer: 'After a claim your no-claim level drops and your premium typically rises at renewal. A no-claim protector add-on can prevent this step-back after one claim per year.' },
    ],

    justificationAttributes: [
      'Clear comparison of WA, WA+, and All-risk coverage levels',
      'Transparent explanation of age-based premium calculation',
      'Dedicated FAQ structure optimized for AI extraction',
      'Practical cost-reduction tips for young drivers',
      'Dutch market focus with correct local terminology',
      'No-claim structure explained clearly',
      'Online quote flow (if available from OHRA)',
    ],

    requiredEvidence: [
      'Current OHRA premium examples for age brackets 18–25',
      'Coverage details for each level (WA, WA+, All-risk)',
      'No-claim discount schedule',
      'Comparison data with at least 2 Dutch market alternatives',
      'Customer review data for young driver segment (if available)',
      'Legal and compliance approval before publishing',
    ],

    competitorAngle:
      'Centraal Beheer and Allianz Direct are currently visible in young-driver comparison queries on Google and in AI-generated answers. OHRA has an opportunity to close this gap by creating a dedicated, structured page with clearer answers, a coverage comparison, and a strong FAQ section that AI assistants can quote directly.',

    schemaRecommendations: ['FAQPage', 'HowTo', 'Product', 'BreadcrumbList'],
  },

  // ─────────────────────────────────────────────────────────────────────────
  'coverage-type': {
    objective:
      'Help Dutch car owners understand the difference between WA, WA+, and All-risk coverage — and help them make the right choice based on their car\'s age and value — positioning OHRA as a trusted, transparent guide in AI search results.',

    targetQueries: [
      '"difference WA WA+ all-risk Netherlands car insurance"',
      '"when to switch from all-risk to WA Netherlands"',
      '"is all-risk worth it for older car Netherlands"',
      '"WA of allrisk autoverzekering wanneer overstappen"',
      '"autoverzekering dekkingsniveau vergelijken"',
    ],

    customerInsight:
      'Dutch car owners are confused by the three coverage levels and frequently ask whether All-risk is still worth paying for older cars. The question typically arises at renewal, when they notice the premium gap between levels. Many are unaware that WA+ exists as a middle option and default to comparing only WA and All-risk.',

    cep: {
      label: 'Choosing coverage level',
      explanation:
        'Every car owner must decide their coverage level at purchase and every renewal. This is a high-frequency, recurring decision moment. Providing a clear, unbiased answer at this moment builds trust and positions OHRA as a helpful advisor rather than just a seller.',
    },

    pageStructure: [
      { type: 'h1',    text: 'WA, WA+ or All-risk: Which Car Insurance Suits You? (Netherlands 2025)' },
      { type: 'block', text: 'Short answer block: one-paragraph summary for AI extraction' },
      { type: 'h2',    text: 'What does WA cover? (minimum legal requirement)' },
      { type: 'h2',    text: 'What does WA+ add?' },
      { type: 'h2',    text: 'What does All-risk cover that WA+ does not?' },
      { type: 'h2',    text: 'Coverage comparison table: WA vs WA+ vs All-risk' },
      { type: 'h2',    text: 'Rule of thumb: when to choose which level' },
      { type: 'h2',    text: 'Frequently asked questions' },
      { type: 'cta',   text: 'Call to action: Calculate your premium / Get a quote' },
    ],

    answerBlock:
      'In the Netherlands, car insurance comes in three levels: WA (mandatory third-party liability), WA+ (adds own damage from external causes like theft, weather, or animal collision), and All-risk (covers your own fault damage too). The right level depends mainly on your car\'s age and value. For cars under four years old, All-risk is usually worth the extra cost. For cars older than seven years, WA is often sufficient. WA+ offers a practical middle ground.',

    faq: [
      { question: 'What is the minimum car insurance required in the Netherlands?',  answer: 'WA (Wettelijke Aansprakelijkheid) is the legal minimum. It covers damage you cause to third parties — their car, property, or injuries. It does not cover damage to your own car.' },
      { question: 'What does WA+ cover that basic WA does not?',                    answer: 'WA+ typically adds coverage for theft, fire, weather damage, glass breakage, and collisions with animals. Damage caused by your own fault is still not covered.' },
      { question: 'Is All-risk worth it for a car that is 5 years old?',            answer: 'It depends on the car\'s current market value. If the car is still worth more than around €10,000, All-risk coverage is generally considered worthwhile. A premium comparison can help make the decision clear.' },
      { question: 'When is a good time to downgrade from All-risk to WA or WA+?',   answer: 'Many Dutch drivers downgrade when their car is 5–7 years old and the annual All-risk premium exceeds roughly 10% of the car\'s value. At that point WA+ often offers better value.' },
      { question: 'Does WA+ cover a hit-and-run in a car park?',                   answer: 'It depends on your specific policy. Many WA+ policies cover damage from unknown third parties (hit-and-run) if you can show evidence. Check your policy terms carefully.' },
      { question: 'Can I change coverage level at any time?',                       answer: 'You can usually upgrade coverage at any time. Downgrading is typically only possible at your renewal date, or in specific circumstances such as a car sale or write-off.' },
    ],

    justificationAttributes: [
      'Clear, unbiased explanation of all three coverage levels',
      'Comparison table optimized for AI extraction',
      'Practical rule of thumb (car age vs. coverage level)',
      'FAQ structure covering common customer confusion points',
      'Dutch insurance terminology used correctly throughout',
      'No sales pressure — educational positioning',
    ],

    requiredEvidence: [
      'OHRA\'s current premium difference between WA, WA+, and All-risk for a sample vehicle',
      'Precise definition of what each level includes and excludes',
      'Examples of covered vs. uncovered scenarios',
      'Legal and compliance review of all coverage claims',
    ],

    competitorAngle:
      'FBTO and Univé rank well in comparison queries for WA vs All-risk. Many answers in AI tools reference Independer\'s comparison tool. OHRA can close this gap by providing a comprehensive, authoritative page with a coverage comparison table — a format AI tools frequently extract and cite.',

    schemaRecommendations: ['FAQPage', 'Article', 'Table', 'BreadcrumbList'],
  },

  // ─────────────────────────────────────────────────────────────────────────
  'ev-insurance': {
    objective:
      'Help Dutch EV owners understand what is different about insuring an electric vehicle, what standard policies miss, and why choosing the right coverage matters — positioning OHRA as a knowledgeable partner for the growing Dutch EV market.',

    targetQueries: [
      '"car insurance for electric vehicle Netherlands"',
      '"does my car insurance cover EV battery damage Netherlands"',
      '"best insurance for Tesla Netherlands"',
      '"autoverzekering elektrische auto batterij gedekt"',
      '"EV verzekering laadpaal diefstal Nederland"',
    ],

    customerInsight:
      'Dutch EV owners are a fast-growing segment with specific insurance concerns: battery damage, charging cable theft, roadside assistance for range anxiety, and high replacement costs. Most are unsure whether their standard car insurance policy covers these EV-specific risks. Very little clear, structured content exists from Dutch insurers to answer these questions.',

    cep: {
      label: 'Switching to electric driving',
      explanation:
        'The moment someone commits to an electric vehicle is a high-intent insurance comparison trigger. EV owners are typically more engaged, research-driven consumers who actively compare policies online and via AI. Being visible and authoritative at this moment gives OHRA a long-term customer acquisition opportunity.',
    },

    pageStructure: [
      { type: 'h1',    text: 'Car Insurance for Electric Vehicles in the Netherlands: What You Need to Know' },
      { type: 'block', text: 'Short answer block: EV insurance in 3 sentences' },
      { type: 'h2',    text: 'How EV insurance differs from petrol car insurance' },
      { type: 'h2',    text: 'Is battery damage covered by standard car insurance?' },
      { type: 'h2',    text: 'Does car insurance cover charging cable theft?' },
      { type: 'h2',    text: 'Roadside assistance for EVs: what to check' },
      { type: 'h2',    text: 'Coverage level recommendation for new EVs' },
      { type: 'h2',    text: 'What OHRA covers for electric vehicles [placeholder — requires compliance review]' },
      { type: 'h2',    text: 'Frequently asked questions' },
      { type: 'cta',   text: 'Call to action: Get an EV insurance quote' },
    ],

    answerBlock:
      'Insuring an electric vehicle in the Netherlands is similar to insuring a petrol car, but with important differences. EV-specific risks include battery damage, charging cable theft, and roadside assistance for charging emergencies. Many standard policies exclude battery degradation, so reviewing the fine print is essential. All-risk coverage is strongly recommended for new EVs due to their high replacement value. As the Dutch EV market grows, more insurers are developing purpose-built EV policies.',

    faq: [
      { question: 'Does standard car insurance cover EV battery damage?',           answer: 'It depends on the cause. Damage from a collision is usually covered by All-risk policies. Battery degradation over time is not covered by any standard insurance policy. Always check your policy terms for specific EV exclusions.' },
      { question: 'Is charging cable theft covered by car insurance?',              answer: 'Some insurers cover charging cable theft as an accessory; others exclude it. This should be explicitly confirmed in your policy. If excluded, a separate home or contents insurance policy may provide coverage.' },
      { question: 'What roadside assistance do I need for an EV?',                 answer: 'EV-specific roadside assistance should include range recovery (transport to a charger if you run out of power), not just mechanical breakdown. Confirm this with your insurer before purchasing.' },
      { question: 'Do I need All-risk coverage for a new electric vehicle?',       answer: 'For a new EV — which can cost €30,000–€80,000 or more — All-risk is strongly recommended. The high replacement and repair costs make the additional premium justifiable.' },
      { question: 'Is leased or company EV insurance different?',                  answer: 'For a leased EV, the leasing company typically sets the minimum required coverage level, often All-risk. Check your lease contract before choosing a policy.' },
      { question: 'Can I insure a Tesla the same way as any other car?',           answer: 'Yes, but Tesla\'s repair costs and parts availability can affect premiums. Some insurers apply surcharges for certain EV brands. Compare quotes specifically for your EV model.' },
    ],

    justificationAttributes: [
      'EV-specific insurance information rarely available from Dutch insurers',
      'Battery damage FAQ — a top AI search query',
      'Charging cable and infrastructure coverage explained',
      'Roadside assistance EV-specific guidance',
      'Dutch EV market focus with correct terminology',
      'FAQ structure for maximum AI extraction potential',
    ],

    requiredEvidence: [
      'OHRA\'s current EV-specific coverage details (battery, cable, roadside)',
      'Premium examples for 2–3 popular EV models in the Netherlands',
      'Explicit statement of what is and is not covered for EVs',
      'Confirmation of roadside assistance terms for EVs',
      'Legal and compliance sign-off on all coverage claims',
    ],

    competitorAngle:
      'Allianz Direct and Centraal Beheer are beginning to create EV-specific content. Most Dutch insurance websites still treat EV and petrol insurance identically. OHRA has a genuine first-mover advantage to become the go-to EV insurance reference for AI tools — which cite sources that provide specific, structured answers to EV questions.',

    schemaRecommendations: ['FAQPage', 'Article', 'Product', 'BreadcrumbList'],
  },

  // ─────────────────────────────────────────────────────────────────────────
  'claim-handling': {
    objective:
      'Help Dutch car owners understand exactly what to do after an accident — step by step — reducing stress at a difficult moment and demonstrating OHRA\'s reliability as an insurer in AI-generated answers.',

    targetQueries: [
      '"how to report a car accident to insurance Netherlands"',
      '"what to do after car accident Netherlands"',
      '"how long does insurance claim take Netherlands"',
      '"schade melden autoverzekering stappenplan"',
      '"hoe lang duurt schadeafhandeling verzekering"',
    ],

    customerInsight:
      'Dutch car owners who have just had an accident are anxious, time-pressed, and searching for immediate, clear answers. They want to know: what to do right now, what forms to fill in, how long it takes, and whether their insurer will be reachable and fair. This is an emotionally charged, high-urgency moment where clear information builds lasting brand trust.',

    cep: {
      label: 'Accident or damage moment',
      explanation:
        'An accident is one of the most stressful moments in a car owner\'s life. Insurers who provide clear, immediate guidance at this moment earn strong loyalty. Competitors who fail to communicate clearly at this moment lose customers. Being the authoritative answer for "what to do after an accident in the Netherlands" gives OHRA a trust advantage that extends far beyond the claim itself.',
    },

    pageStructure: [
      { type: 'h1',    text: 'What to Do After a Car Accident in the Netherlands: Step-by-Step Guide' },
      { type: 'block', text: 'Short answer block: 5-step summary for AI extraction' },
      { type: 'h2',    text: 'Step 1: Secure the scene and check for injuries' },
      { type: 'h2',    text: 'Step 2: Complete the accident report form (schadeformulier)' },
      { type: 'h2',    text: 'Step 3: Report the claim to your insurer' },
      { type: 'h2',    text: 'Step 4: What happens during the claims assessment?' },
      { type: 'h2',    text: 'Step 5: Repair and payment — how it works' },
      { type: 'h2',    text: 'How long does a claim take? (typical timelines)' },
      { type: 'h2',    text: 'Frequently asked questions' },
      { type: 'cta',   text: 'Call to action: Report a claim now / Contact OHRA' },
    ],

    answerBlock:
      'After a car accident in the Netherlands, secure the scene first and check for injuries. Exchange details with the other driver and complete a schadeformulier (accident report form). Report the claim to your insurer within three business days, with photos and witness details if available. Your insurer will assess the damage and communicate next steps. Straightforward claims are typically resolved within two to four weeks. If the other party was at fault and is insured, their insurer covers your repair costs.',

    faq: [
      { question: 'What is the first thing to do after a car accident?',            answer: 'Ensure the scene is safe, switch on hazard lights, and check for injuries. Call emergency services (112) if anyone is hurt. Do not move vehicles until the scene is documented.' },
      { question: 'What is a schadeformulier and do I need one?',                   answer: 'A schadeformulier is a standardized European accident report form. Both drivers complete and sign it at the scene. It documents who was involved, what happened, and who may be at fault. Always carry one in your car.' },
      { question: 'How quickly do I need to report a claim?',                       answer: 'Most Dutch insurers require a claim to be reported within 3 to 7 days. Check your policy terms. Delaying a claim without a valid reason can affect your coverage.' },
      { question: 'What happens if the other driver drives away (hit-and-run)?',    answer: 'Report the incident to the police immediately and contact your insurer. Depending on your coverage level (WA+ or All-risk), your insurer may cover damage caused by an unidentified third party.' },
      { question: 'How long does a car insurance claim take in the Netherlands?',   answer: 'Simple claims (clear liability, no injuries) are often resolved in 1–4 weeks. Complex claims involving disputes or injuries can take several months. Your insurer should provide a timeline after the initial assessment.' },
      { question: 'Will my premium increase after making a claim?',                 answer: 'Yes, in most cases. A claim causes your no-claim level to drop, which results in a higher premium at renewal. A no-claim protector add-on can limit this impact.' },
    ],

    justificationAttributes: [
      'Clear, actionable step-by-step format optimized for AI extraction',
      'Schadeformulier guidance — a high-frequency Dutch search query',
      'Timeline transparency builds trust',
      'Hit-and-run FAQ covers an emotionally important edge case',
      'Premium impact explained honestly',
    ],

    requiredEvidence: [
      'OHRA\'s actual claim reporting procedure and channels',
      'Realistic claim processing timelines from OHRA\'s data',
      'Accurate no-claim impact after claim (by policy type)',
      'Confirmation of which claim types affect no-claim score',
      'Legal and compliance review of all claim procedure descriptions',
    ],

    competitorAngle:
      'ANWB and Centraal Beheer have step-by-step claim guides that are frequently cited in AI search results. OHRA currently lacks this type of structured, urgency-aware content. A clear how-to page with HowTo schema markup is one of the highest-impact content investments OHRA could make for both human searchers and AI engines.',

    schemaRecommendations: ['HowTo', 'FAQPage', 'Article', 'BreadcrumbList'],
  },

  // ─────────────────────────────────────────────────────────────────────────
  'switching': {
    objective:
      'Help Dutch car owners who are dissatisfied with their current insurer — especially after a premium increase — understand how easy it is to switch, and position OHRA as the logical next step in AI-generated answers.',

    targetQueries: [
      '"how to switch car insurance Netherlands"',
      '"can I switch car insurance after premium increase Netherlands"',
      '"autoverzekering overstappen na premieverhoging"',
      '"beste alternatief voor Centraal Beheer autoverzekering"',
      '"overstappen autoverzekering stap voor stap"',
    ],

    customerInsight:
      'Dutch car owners who receive a premium increase notice are in a high-intent, emotionally motivated switching moment. They are actively searching for alternatives and want to know: can I switch now, will I lose my no-claim discount, and how hard is it? The window of intent is short — typically the weeks immediately after receiving a renewal notice. Clear, fast answers that remove switching friction convert directly to new customers.',

    cep: {
      label: 'Renewal or dissatisfaction moment',
      explanation:
        'A premium increase triggers immediate comparison behavior. This CEP is commercially the most valuable for OHRA: the prospect is already motivated, has already decided to look, and just needs a reason to choose OHRA over a competitor. Content that answers "how do I switch?" at this moment can capture customers at the highest-intent point in their buying journey.',
    },

    pageStructure: [
      { type: 'h1',    text: 'How to Switch Car Insurance in the Netherlands: Easy Step-by-Step Guide' },
      { type: 'block', text: 'Short answer block: switching in 3 steps' },
      { type: 'h2',    text: 'When can you switch car insurance in the Netherlands?' },
      { type: 'h2',    text: 'Can I switch immediately after a premium increase?' },
      { type: 'h2',    text: 'Step-by-step: how to switch to OHRA' },
      { type: 'h2',    text: 'What happens to your no-claim discount when you switch?' },
      { type: 'h2',    text: 'What you need to arrange before switching' },
      { type: 'h2',    text: 'Frequently asked questions' },
      { type: 'cta',   text: 'Call to action: Switch to OHRA today / Get a quote in 3 minutes' },
    ],

    answerBlock:
      'Switching car insurance in the Netherlands is possible at your annual renewal date, or immediately in specific situations such as a premium increase, car sale, or relocation. Most policies require 30 days written notice before cancellation. To switch: compare alternatives, confirm your new insurer\'s start date, cancel your current policy in writing, and transfer your no-claim certificate. The entire process can be completed online in under an hour, with your new coverage active the next business day.',

    faq: [
      { question: 'Can I switch car insurance at any time in the Netherlands?',     answer: 'In most cases you can switch at your annual renewal date. You can also switch mid-term if your insurer raises your premium, if you sell the car, or if you move abroad.' },
      { question: 'Can I switch immediately if my insurer raises my premium?',      answer: 'Yes. Dutch law gives you the right to cancel your policy within 30 days of receiving a premium increase notice. This allows you to switch before the new rate takes effect.' },
      { question: 'Will I keep my no-claim discount when I switch insurer?',        answer: 'Yes. Your no-claim history is recorded in the Dutch Bonus-Malus register. Your new insurer will request this information directly. You do not lose your no-claim discount by switching.' },
      { question: 'How much notice do I need to give my current insurer?',          answer: 'Most policies require 30 days written notice. Check your current policy documents for the exact cancellation terms.' },
      { question: 'What documents do I need to switch car insurance?',              answer: 'You typically need: your current policy number, your no-claim certificate (or the insurer will request it), your vehicle registration (kentekenbewijs), and your driving licence details.' },
      { question: 'Is there a gap in coverage when switching insurers?',            answer: 'No, if you coordinate the dates correctly. Set your new policy start date to the same day your old policy ends. Your new insurer can usually arrange this if you give them your intended switch date.' },
    ],

    justificationAttributes: [
      'Removes switching friction with a clear step-by-step format',
      'Explains no-claim transfer — a major concern that prevents switching',
      'Premium increase opt-out right explained (Dutch consumer right)',
      'Practical document checklist',
      'FAQ answers the top objections to switching',
      'Optimized for high-intent "how to switch" queries in AI search',
    ],

    requiredEvidence: [
      'OHRA\'s actual switching/onboarding process and timeline',
      'Confirmation that OHRA requests no-claim certificate from Bonus-Malus register',
      'Specific cancellation notice requirements from OHRA\'s policy terms',
      'Legal basis for mid-term cancellation rights after premium increase',
      'Legal and compliance approval before publishing',
    ],

    competitorAngle:
      'Independer and InShared\'s comparison tools capture many switching-intent users before they ever reach OHRA\'s website. AI tools frequently cite Independer\'s switching guides when users ask "how do I switch car insurance in the Netherlands". A dedicated OHRA switching guide with HowTo schema could intercept this traffic directly in AI answers, bypassing comparison platforms.',

    schemaRecommendations: ['HowTo', 'FAQPage', 'Product', 'BreadcrumbList'],
  },
}
